name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  CI:
    runs-on: ubuntu-latest
    container: heliumsystems/builder-erlang:1

    steps:
      - uses: actions/checkout@v2

      - name: Fetch git tags
        run: git fetch --prune --unshallow --tags

      - name: Build
        run: rebar3 compile

      - name: Run Dialyzer
        run: rebar3 do dialyzer, xref

      - name: Run tests
        run: rebar3 eunit

      - name: Generate coverage report
        run: rebar3 covertool generate

      - name: Upload coverage report
        uses: codecov/codecov-action@v1
        with:
          file: _build/test/covertool/libp2p_crypto.covertool.xml
          fail_ci_if_error: true
